//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace ServiceClientLayer.JustEatWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webservicesSoap", Namespace="http://just-eat.com/")]
    public partial class webservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRestaurantListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRestaurantDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllPostcodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryAreaServerValidationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webservices() {
            this.Url = global::ServiceClientLayer.Properties.Settings.Default.ServiceClientLayer_JustEatWebService_webservices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRestaurantListCompletedEventHandler getRestaurantListCompleted;
        
        /// <remarks/>
        public event getRestaurantDataCompletedEventHandler getRestaurantDataCompleted;
        
        /// <remarks/>
        public event getAllPostcodesCompletedEventHandler getAllPostcodesCompleted;
        
        /// <remarks/>
        public event DeliveryAreaServerValidationCompletedEventHandler DeliveryAreaServerValidationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://just-eat.com/getRestaurantList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://just-eat.com/")]
        public System.Xml.XmlNode getRestaurantList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://just-eat.com/")] string postcode) {
            object[] results = this.Invoke("getRestaurantList", new object[] {
                        postcode});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getRestaurantListAsync(string postcode) {
            this.getRestaurantListAsync(postcode, null);
        }
        
        /// <remarks/>
        public void getRestaurantListAsync(string postcode, object userState) {
            if ((this.getRestaurantListOperationCompleted == null)) {
                this.getRestaurantListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRestaurantListOperationCompleted);
            }
            this.InvokeAsync("getRestaurantList", new object[] {
                        postcode}, this.getRestaurantListOperationCompleted, userState);
        }
        
        private void OngetRestaurantListOperationCompleted(object arg) {
            if ((this.getRestaurantListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRestaurantListCompleted(this, new getRestaurantListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://just-eat.com/getRestaurantData", RequestNamespace="http://just-eat.com/", ResponseNamespace="http://just-eat.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getRestaurantData(int restaurantId, string postcode) {
            object[] results = this.Invoke("getRestaurantData", new object[] {
                        restaurantId,
                        postcode});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getRestaurantDataAsync(int restaurantId, string postcode) {
            this.getRestaurantDataAsync(restaurantId, postcode, null);
        }
        
        /// <remarks/>
        public void getRestaurantDataAsync(int restaurantId, string postcode, object userState) {
            if ((this.getRestaurantDataOperationCompleted == null)) {
                this.getRestaurantDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRestaurantDataOperationCompleted);
            }
            this.InvokeAsync("getRestaurantData", new object[] {
                        restaurantId,
                        postcode}, this.getRestaurantDataOperationCompleted, userState);
        }
        
        private void OngetRestaurantDataOperationCompleted(object arg) {
            if ((this.getRestaurantDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRestaurantDataCompleted(this, new getRestaurantDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://just-eat.com/getAllPostcodes", RequestNamespace="http://just-eat.com/", ResponseNamespace="http://just-eat.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getAllPostcodes() {
            object[] results = this.Invoke("getAllPostcodes", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getAllPostcodesAsync() {
            this.getAllPostcodesAsync(null);
        }
        
        /// <remarks/>
        public void getAllPostcodesAsync(object userState) {
            if ((this.getAllPostcodesOperationCompleted == null)) {
                this.getAllPostcodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllPostcodesOperationCompleted);
            }
            this.InvokeAsync("getAllPostcodes", new object[0], this.getAllPostcodesOperationCompleted, userState);
        }
        
        private void OngetAllPostcodesOperationCompleted(object arg) {
            if ((this.getAllPostcodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllPostcodesCompleted(this, new getAllPostcodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://just-eat.com/DeliveryAreaServerValidation", RequestNamespace="http://just-eat.com/", ResponseNamespace="http://just-eat.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeliveryAreaServerValidation(string postcode, int restaurantId, string orderType) {
            object[] results = this.Invoke("DeliveryAreaServerValidation", new object[] {
                        postcode,
                        restaurantId,
                        orderType});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryAreaServerValidationAsync(string postcode, int restaurantId, string orderType) {
            this.DeliveryAreaServerValidationAsync(postcode, restaurantId, orderType, null);
        }
        
        /// <remarks/>
        public void DeliveryAreaServerValidationAsync(string postcode, int restaurantId, string orderType, object userState) {
            if ((this.DeliveryAreaServerValidationOperationCompleted == null)) {
                this.DeliveryAreaServerValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryAreaServerValidationOperationCompleted);
            }
            this.InvokeAsync("DeliveryAreaServerValidation", new object[] {
                        postcode,
                        restaurantId,
                        orderType}, this.DeliveryAreaServerValidationOperationCompleted, userState);
        }
        
        private void OnDeliveryAreaServerValidationOperationCompleted(object arg) {
            if ((this.DeliveryAreaServerValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryAreaServerValidationCompleted(this, new DeliveryAreaServerValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRestaurantListCompletedEventHandler(object sender, getRestaurantListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRestaurantListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRestaurantListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getRestaurantDataCompletedEventHandler(object sender, getRestaurantDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRestaurantDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRestaurantDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getAllPostcodesCompletedEventHandler(object sender, getAllPostcodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllPostcodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllPostcodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeliveryAreaServerValidationCompletedEventHandler(object sender, DeliveryAreaServerValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryAreaServerValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryAreaServerValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591